# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: common.proto
"""Generated protocol buffer code."""
from . google.protobuf from . import descriptor as _descriptor
from . google.protobuf from . import message as _message
from . google.protobuf from . import reflection as _reflection
from . google.protobuf from . import symbol_database as _symbol_database
# @@protoc_insertion_point(from . imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='common.proto',
  package='main',
  syntax='proto3',
  serialized_options=b'H\003Z\020example.com;main',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0c\x63ommon.proto\x12\x04main\"$\n\x08IntRange\x12\x0b\n\x03Min\x18\x01 \x01(\t\x12\x0b\n\x03Max\x18\x02 \x01(\tB\x14H\x03Z\x10\x65xample.com;mainb\x06proto3'
)




_INTRANGE = _descriptor.Descriptor(
  name='IntRange',
  full_name='main.IntRange',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='Min', full_name='main.IntRange.Min', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='Max', full_name='main.IntRange.Max', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=22,
  serialized_end=58,
)

DESCRIPTOR.message_types_by_name['IntRange'] = _INTRANGE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

IntRange = _reflection.GeneratedProtocolMessageType('IntRange', (_message.Message,), {
  'DESCRIPTOR' : _INTRANGE,
  '__module__' : 'common_pb2'
  # @@protoc_insertion_point(class_scope:main.IntRange)
  })
_sym_db.RegisterMessage(IntRange)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
