# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: common_from . imported.proto
"""Generated protocol buffer code."""
from . google.protobuf from . import descriptor as _descriptor
from . google.protobuf from . import message as _message
from . google.protobuf from . import reflection as _reflection
from . google.protobuf from . import symbol_database as _symbol_database
# @@protoc_insertion_point(from . imports)

_sym_db = _symbol_database.Default()


from . import common_pb2 as common__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='common_from . imported.proto',
  package='main',
  syntax='proto3',
  serialized_options=b'H\003Z\020example.com;main',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x15\x63ommon_from . imported.proto\x12\x04main\x1a\x0c\x63ommon.proto\".\n\nUsesCommon\x12 \n\x08IntRange\x18\x01 \x01(\x0b\x32\x0e.main.IntRangeB\x14H\x03Z\x10\x65xample.com;mainb\x06proto3'
  ,
  dependencies=[common__pb2.DESCRIPTOR,])




_USESCOMMON = _descriptor.Descriptor(
  name='UsesCommon',
  full_name='main.UsesCommon',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='IntRange', full_name='main.UsesCommon.IntRange', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=45,
  serialized_end=91,
)

_USESCOMMON.fields_by_name['IntRange'].message_type = common__pb2._INTRANGE
DESCRIPTOR.message_types_by_name['UsesCommon'] = _USESCOMMON
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

UsesCommon = _reflection.GeneratedProtocolMessageType('UsesCommon', (_message.Message,), {
  'DESCRIPTOR' : _USESCOMMON,
  '__module__' : 'common_from . imported_pb2'
  # @@protoc_insertion_point(class_scope:main.UsesCommon)
  })
_sym_db.RegisterMessage(UsesCommon)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
