// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: TestProtobuf.proto

#include "TestProtobuf.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/io/zero_copy_stream_impl_lite.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG

namespace _pb = ::PROTOBUF_NAMESPACE_ID;
namespace _pbi = _pb::internal;

namespace main {
PROTOBUF_CONSTEXPR NewMessege::NewMessege(
    ::_pbi::ConstantInitialized)
  : bools_()
  , onestring_(&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{})
  , oneint_(0){}
struct NewMessegeDefaultTypeInternal {
  PROTOBUF_CONSTEXPR NewMessegeDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~NewMessegeDefaultTypeInternal() {}
  union {
    NewMessege _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 NewMessegeDefaultTypeInternal _NewMessege_default_instance_;
}  // namespace main
namespace main {

// ===================================================================

class NewMessege::_Internal {
 public:
};

NewMessege::NewMessege(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::MessageLite(arena, is_message_owned),
  bools_(arena) {
  SharedCtor();
  // @@protoc_insertion_point(arena_constructor:main.NewMessege)
}
NewMessege::NewMessege(const NewMessege& from)
  : ::PROTOBUF_NAMESPACE_ID::MessageLite(),
      bools_(from.bools_) {
  _internal_metadata_.MergeFrom<std::string>(from._internal_metadata_);
  onestring_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    onestring_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_onestring().empty()) {
    onestring_.Set(from._internal_onestring(), 
      GetArenaForAllocation());
  }
  oneint_ = from.oneint_;
  // @@protoc_insertion_point(copy_constructor:main.NewMessege)
}

inline void NewMessege::SharedCtor() {
onestring_.InitDefault();
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  onestring_.Set("", GetArenaForAllocation());
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
oneint_ = 0;
}

NewMessege::~NewMessege() {
  // @@protoc_insertion_point(destructor:main.NewMessege)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<std::string>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void NewMessege::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  onestring_.Destroy();
}

void NewMessege::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}

void NewMessege::Clear() {
// @@protoc_insertion_point(message_clear_start:main.NewMessege)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  bools_.Clear();
  onestring_.ClearToEmpty();
  oneint_ = 0;
  _internal_metadata_.Clear<std::string>();
}

const char* NewMessege::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // string OneString = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 10)) {
          auto str = _internal_mutable_onestring();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, nullptr));
        } else
          goto handle_unusual;
        continue;
      // int32 OneInt = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 16)) {
          oneint_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // repeated bool Bools = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 26)) {
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::PackedBoolParser(_internal_mutable_bools(), ptr, ctx);
          CHK_(ptr);
        } else if (static_cast<uint8_t>(tag) == 24) {
          _internal_add_bools((bool)::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr));
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<std::string>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* NewMessege::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:main.NewMessege)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // string OneString = 1;
  if (!this->_internal_onestring().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_onestring().data(), static_cast<int>(this->_internal_onestring().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "main.NewMessege.OneString");
    target = stream->WriteStringMaybeAliased(
        1, this->_internal_onestring(), target);
  }

  // int32 OneInt = 2;
  if (this->_internal_oneint() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt32ToArray(2, this->_internal_oneint(), target);
  }

  // repeated bool Bools = 3;
  if (this->_internal_bools_size() > 0) {
    target = stream->WriteFixedPacked(3, _internal_bools(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = stream->WriteRaw(_internal_metadata_.unknown_fields<std::string>(::PROTOBUF_NAMESPACE_ID::internal::GetEmptyString).data(),
        static_cast<int>(_internal_metadata_.unknown_fields<std::string>(::PROTOBUF_NAMESPACE_ID::internal::GetEmptyString).size()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:main.NewMessege)
  return target;
}

size_t NewMessege::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:main.NewMessege)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // repeated bool Bools = 3;
  {
    unsigned int count = static_cast<unsigned int>(this->_internal_bools_size());
    size_t data_size = 1UL * count;
    if (data_size > 0) {
      total_size += 1 +
        ::_pbi::WireFormatLite::Int32Size(static_cast<int32_t>(data_size));
    }
    total_size += data_size;
  }

  // string OneString = 1;
  if (!this->_internal_onestring().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_onestring());
  }

  // int32 OneInt = 2;
  if (this->_internal_oneint() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(this->_internal_oneint());
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    total_size += _internal_metadata_.unknown_fields<std::string>(::PROTOBUF_NAMESPACE_ID::internal::GetEmptyString).size();
  }
  int cached_size = ::_pbi::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void NewMessege::CheckTypeAndMergeFrom(
    const ::PROTOBUF_NAMESPACE_ID::MessageLite& from) {
  MergeFrom(*::_pbi::DownCast<const NewMessege*>(
      &from));
}

void NewMessege::MergeFrom(const NewMessege& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:main.NewMessege)
  GOOGLE_DCHECK_NE(&from, this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  bools_.MergeFrom(from.bools_);
  if (!from._internal_onestring().empty()) {
    _internal_set_onestring(from._internal_onestring());
  }
  if (from._internal_oneint() != 0) {
    _internal_set_oneint(from._internal_oneint());
  }
  _internal_metadata_.MergeFrom<std::string>(from._internal_metadata_);
}

void NewMessege::CopyFrom(const NewMessege& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:main.NewMessege)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool NewMessege::IsInitialized() const {
  return true;
}

void NewMessege::InternalSwap(NewMessege* other) {
  using std::swap;
  auto* lhs_arena = GetArenaForAllocation();
  auto* rhs_arena = other->GetArenaForAllocation();
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  bools_.InternalSwap(&other->bools_);
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &onestring_, lhs_arena,
      &other->onestring_, rhs_arena
  );
  swap(oneint_, other->oneint_);
}

std::string NewMessege::GetTypeName() const {
  return "main.NewMessege";
}


// @@protoc_insertion_point(namespace_scope)
}  // namespace main
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::main::NewMessege*
Arena::CreateMaybeMessage< ::main::NewMessege >(Arena* arena) {
  return Arena::CreateMessageInternal< ::main::NewMessege >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
