name: UPM Sync
on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  build-unity:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Config
        run: |
          git config --local user.email "contact@gameworkstore.com"
          git config --local user.name "game-workstore-bot"
      - name: Push downstream aws-network-engine-go package
        uses: NxtLvLSoftware/git-subtree-action@1.1
        with:
          repo: GameWorkstore/google-protobuf-unity
          path: ProtobufUnitySDK/Assets/Package
          deploy_key: ${{ secrets.GOOGLE_PROTOBUF_DEPLOY_KEY }}
          force: true
          branch: upm